---
# tasks file for add-deb-repo

- name: Add repository gpg key by server url
  apt_key:
    keyserver: "{{ gpg_key.repository_url }}"
    id: "{{ gpg_key.id }}"
    state: present
  when: gpg_key.repository_url is defined

- name: Add repository gpg key by key url
  apt_key:
    url: "{{ gpg_key.key_url }}"
    state: present
  when: gpg_key.key_url is defined

- name: Add repository
  apt_repository:
    repo: "deb {{ deb_repository.url }} {{ deb_repository.options}}"
    state: present
    update_cache: yes
